name: Publish Docker Image to Docker Hub 🚀

on:
    push:
        branches: ['testing']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/talent-pro-backend

            - name: Docker Push
              run: docker push ${{ secrets.DOCKER_USERNAME }}/talent-pro-backend
    deploy:
        runs-on: ip-172-31-38-150

        steps:
            - name: Pull image from docker hub
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/talent-pro-backend:latest
            - name: Delete old container
              run: docker rm -f talent-pro-server
            - name: Run docker container
              run: docker run -d -p 5000:5000 --name talent-pro-server ${{ secrets.DOCKER_USERNAME }}/talent-pro-backend
